### ISSUE TITLE
New ip addresses to add 18-04-2022

### ISSUE THREAD

**Issue by mjanssens** [astromeier/LetsEncrypt_Serverlist#2]
Hi, thanks for maintaining until now.
I just did a server migration and ran a forced renewal for letsencrypt and found out my opnsense firewall was blocking it during secondary validation.
So I ran it several times and the following ip addresses seem new and did 3 attempts every time.
I put them in an extra host list to allow them to pass and the validation process went fine now.
There could be more addresses, but these were the ones I got. You should probably doublecheck them before committing them.

34.216.192.11
13.59.153.150
54.93.194.3
128.14.209.164
54.201.106.94
3.70.226.171
52.25.138.85
3.133.99.173
18.192.99.12
103.112.226.84
3.21.43.5

**Comment by astromeier** [comment]
Hi, i did a quick check and found at least 4 abusive IPs (checked with https://www.abuseipdb.com). 
All residual addresses could be candidates - I'll check them the next weeks. The IPs of A100 ROW are good candidates!
Please do the same and cross-check the HA-Proxy-Log for acme accesses with correct key (same as challenge)

**Comment by mjanssens** [comment]
good job doublechecking.
I analyzed my apache logs (I run certbot with apache)
These are the IPs actually communicating with correct key:

3.70.226.171
3.21.43.5
66.133.109.36 (outbound1.letsencrypt.org)
54.201.106.94

**Comment by astromeier** [comment]
Hi!
I could commit 6 IPs. The serverlist was updated....
