### ISSUE TITLE
New ip addresses to add 30-06-2022

### ISSUE THREAD

**Issue by mjanssens** [astromeier/LetsEncrypt_Serverlist#3]
Thanks for updating https://github.com/astromeier/LetsEncrypt_Serverlist/commit/6d6db9891c2c7d78ea71d88e562b5fb07cc015aa a few days ago.
Today however I got a notice that my cert validation failed .
So I found 3 other ip addresses that are candidates to be added.

34.220.126.78
3.131.99.217
3.70.173.52

Tried without adding them and  the same addresses were used every time.
After allowing these 3 my certs were validated again.
Please review and add them if they pass your health checks.

Thanks

**Comment by astromeier** [comment]
Thanks for contribution!
5 new addresses are noticed to me and I will check them.

Maybe these IP are dependent to the location of the verify request...

**Comment by mjanssens** [comment]
> Maybe these IP are dependent to the location of the verify request...

That was my thought too.

**Comment by astromeier** [comment]
Please let me know new IPs so I can add them!
