### ISSUE TITLE
duplicate ip causes ipset restore to stop

### ISSUE THREAD

**Issue by allobrogica** [astromeier/LetsEncrypt_Serverlist#4]
The current serverlist has the IP 3.125.19.113 listed twice. This causes ipset restore to fail/stop (with only doing partial restore). Best to make sure no duplicates are in the list. However, one can use "ipset restore -exist" to ignore any duplicates.

**Comment by astromeier** [comment]
Thanks! Duplicate deleted....

**Comment by astromeier** [comment]
closed
