### ISSUE TITLE
New ip addresses to add (asia region)

### ISSUE THREAD

**Issue by allobrogica** [astromeier/LetsEncrypt_Serverlist#5]
These IPs were needed (two separate caddy runs) from Singapore region. Please add to the list.

18.192.245.0
23.178.112.106
18.221.77.37
34.220.129.39

52.58.148.172
3.19.55.121
23.178.112.208
54.191.60.25

**Comment by astromeier** [comment]
Thanks! 
 23.178.112.106 and  23.178.112.208 are in FQDN list. The others are added in IP List.
Great contribution - thanks again!

**Comment by astromeier** [comment]
closed
